# Generated by Django 5.2.7 on 2025-11-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
